name: Build ICS

on:
  push:
  schedule:
    - cron: "0 0 1 1 *"  # every Jan 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install python-dateutil

      - name: Generate ICS
        run: python generate.py

      - name: Commit file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add feriados_FLN.ics
          git commit -m "update ICS" || exit 0
          git push
